on:
  push:
    branches: main
    tags:
      - 'hoge-*'
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-node-${{ hashFiles('**/package-lock.json') }}
        if: ${{ github.repository == 'dummy' }}
      - run: npm install && npm test
