on:
  issues: {types: opened}
  
jobs:
  comment:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '? Thanks for reporting!'
            })
