name: reviewdog/action-actionlint
on: 
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  actionlint1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install shellcheck to enable shellcheck integration
        run: sudo apt install shellcheck

      - name: Download actionlint
        id: get_actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash

  reviewdog_actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1

